name: Villainy Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
  
    env:
      VULKAN_VERSION: 1.4.341.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        timeout-minutes: 10
        with: 
          lfs: true
      
      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake ninja-build
      
      - name: Install build dependencies (MacOS)
        if: runner.os == 'macOS'
        run: brew install cmake ninja

      - name: Setup Vulkan SDK (Linux)
        if: runner.os == 'Linux'
        run: |
          wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
          sudo apt update
          sudo apt install -y vulkan-sdk
      
      - name: Setup Vulkan SDK (Windows)
        if: runner.os == 'Windows'
        run: |
          $url = "https://sdk.lunarg.com/sdk/download/$env:VULKAN_VERSION/windows/vulkansdk-windows-X64-$env:VULKAN_VERSION.exe"
          Invoke-WebRequest -Uri $url -OutFile VulkanSDK.exe
          .\VulkanSDK.exe /S
          echo "VULKAN_SDK=C:\VulkanSDK\$env:VULKAN_VERSION" >> $env:GITHUB_ENV
        
      - name: Setup Vulkan SDK (MacOS)
        if: runner.os == 'macOS'
        run: |
          wget https://sdk.lunarg.com/sdk/download/$env:VULKAN_VERSION/mac/vulkansdk-macos-$env:VULKAN_VERSION.zip
          unzip vulkansdk-macos-$env:VULKAN_VERSION.zip -d ~/VulkanSDK
          sudo ~/VulkanSDK/vulkansdk-macos-$env:VULKAN_VERSION/InstallVulkan.app/Contents/MacOS/InstallVulkan --root ~/VulkanSDK --accept-licenses --default-answer --confirm-command install
          echo "VULKAN_SDK=$HOME/VulkanSDK/macOS" >> $GITHUB_ENV
      
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release